version: '3'
services:

  de_lanserver:
    image: de_lanserver:latest
    container_name: de_lanserver
    ports:
      - "217.160.255.254:8443:8443"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.6

    build:
      context: ./
      dockerfile: Dockerfile


    environment:
      - TZ=Europe/Berlin
    dns:
    - 208.67.222.222
    - 208.67.220.220
    - 208.67.220.222
    - 208.67.222.220


networks:
  192.168.178.0:
    external: true



