version: '3'


services:

  lanserver:
    image: imglanserver:latest
    container_name: lanserver
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "217.160.255.254:8443:8443"




