version: '3.8'
services:
  demolanserver:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8443:8443
      - 9092:9092
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"


