version: '2'
services:
  jgsoftwares:
    container_name: demolanver

    image: jgsoftwares/jgsoftwares:demolanserver
    ports:
      - 8443:8888
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge